# Generated by Django 3.0.7 on 2020-06-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='document',
            field=models.FileField(upload_to='static/documents/'),
        ),
    ]
